name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: setup
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - id: install
        name: Install dependencies
        run: npm i

      - id: test
        name: Run tests
        run: npm run test
        env:
          OPTA_OUTLET_AUTH: ${{ secrets.OPTA_OUTLET_AUTH }}
          OPTA_SECRET_KEY: ${{ secrets.OPTA_SECRET_KEY }}
